# Default Project Configuration

title="Configuration"

[logging]
version = 1
disable_existing_loggers = true
[logging.formatters.verbose]
format = '%(levelname)s %(name)s: %(message)s'
[logging.formatters.simple]
format = '%(levelname)s: %(message)s'
[logging.handlers.default]
level = 'INFO'
formatter = 'simple'
class = 'logging.StreamHandler'
stream = 'ext://sys.stdout'
[logging.root]
handlers = ['default']
level = 'WARN'
[logging.loggers.claimscrape]
level = 'INFO'
